### ISSUE TITLE
Mapping values containing undescores are allways written in capital after the underscore

### ISSUE THREAD

**Issue by niklaskks** [axsemantics/axsemantics-python#2]
The data field "vehicle_type" in the xlsx file becomes "vehicle_Type".
This occcurs independant of .xlsx file or targeted Content Project.

**Comment by rixx** [comment]
And the wanted behaviour is for the value to remain as 'vehicle_type'?

**Comment by rixx** [comment]
fixed, and removed all other automatic capitalization as well. ('vehicle type' will be renamed to 'vehicletype' instead of 'vehicleType' now).
